### ISSUE TITLE
Add JDBI support

### ISSUE THREAD

**Issue by miere** [Skullabs/kikaha#113]
## Context
JDBI seems to be a great tool to handle SQL queries. Today, in order to integrate with Kikaha, it requires developers to write a lot of boilerplate classes.

## Definition of done
The following points should be considered while implementing this module:
- Developers should be able to use it with (almost) no configuration at all.
- It should be able to consume any configured ```DataSource``` made available by the ```kikaha-db``` module.
- Should be possible to map columns through Java Annotations, just like JPA does.
- It should neither be complex nor hide queries from the developer.
- Developers could, optionally, write their own JDBI Mappers if needed.
- It should use the most updated JDBI version.

**Comment by sizebay** [comment]
Hi @miere, as you already know (as you work with us), we use JDBI a lot here.
Could you please update the **definition of done** of this feature? May be, we can open source the JDBI-related routines we have here that does not expose our business logic.

**Comment by miere** [comment]
Hi @sizebay 
I just updated the **dod** of this issue. I'm removing this issue from the current milestone, once it will be provided as a "contrib" module.

**Comment by miere** [comment]
I'm closing this issue once the @sizebay 's module is already open sourced [here](https://github.com/sizebay/sizebay-kikaha-jdbi).
