### ISSUE TITLE
Missing Mustache module documentation

### ISSUE THREAD

**Issue by marspessoa** [Skullabs/kikaha#121]
I cant find any documentation about mustache templating module at the kikaha's documentation page.

**Comment by miere** [comment]
Indeed, Marcos, it is missing.

Actually, it still missing some documentation for other pieces of the framework like DefaultResponse API, the Mustache module itself, the access database module... We are quite sorry about that, but last days were (at least me) very overwhelming.

We will update the documentation for the next 1.6.0 release.

**Comment by marspessoa** [comment]
And the chedule for 1.6.0 release, will be?

**Comment by spencode** [comment]
Hi.

When the written documentation?
Already version Versions 1.6.1

**Comment by miere** [comment]
Actually, the documentation will be ready in the next couple weeks.
In the last month I've been working at the Kikaha's command line tool to automate some repetitive tasks.

This month we should include at the documentation:
- Hazelcast Integration
- Mustache templates
- DB configurations with ViburDBCP

**Comment by miere** [comment]
@spencode @marspessoa 

I just created an issue do group all these documentation gaps.
Please, feel free to submit other issues regarding this, okay?

Best regards!

**Comment by miere** [comment]
Documentation topic added [here](http://kikaha.skullabs.io/docs/constructing-html-with-mustache-templates).

@spencode @marspessoa I'll keep watching this issue. Please fill free to ask me if you have any doubt about mustache templates.
