### ISSUE TITLE
http://kikaha.skullabs.io/ is unavailable

### ISSUE THREAD

**Issue by lospejos** [Skullabs/kikaha#136]
http://kikaha.skullabs.io/ is unavailble

**Comment by miere** [comment]
Thanks for notify me. The Kikaha's documentation is hosted on [readme.io](http://readme.io). Maybe it could be an outage issue of readme.io. I've contacted them right now, I'll wait for they response about this topic before close this issue.

**Comment by miere** [comment]
As far as support team from readme.io knows, they didn't received any feedback about outage. Please, @lospejos keep in touch if it happens again.

Best regards.
