### ISSUE TITLE
WebSocket example compilation error: "illegal start of expression"

### ISSUE THREAD

**Issue by fohara** [Skullabs/kikaha#160]
Following the guide here http://kikaha.skullabs.io/v2.0.0/docs/web-socket-routing (though I have also reproduced this with v1.6), I attempt to compile the code below via `kikaha build`:
```java
package foo;

import kikaha.urouting.api.*;

@WebSocket( "chat/{room-id}" )
public class ChatResource {

    @OnMessage
    public void onMessage( WebSocketSession session, String message ) {
        session.broadcast( session.getUserPrincipal() + " just sent: " + message );
    }

    @OnOpen
    public void onOpen( WebSocketSession session ) {
        session.broadcast( session.getUserPrincipal() + " has entered into the chat room" );
    }

    @OnError
    public void onError( final Throwable cause ) {
        System.err.println( cause.getMessage() );
    }

    @OnClose
    public void onClose( WebSocketSession session, CloseMessage cm ) {
        session.broadcast( session.getUserPrincipal() + " left the chat room" );
    }
}
```
And I get the following compilation errors:
```
[ERROR] /.../output/generated-sources/annotations/foo/GeneratedWebSocket424482473.java:[42,25] illegal start of expression
[ERROR] /.../output/generated-sources/annotations/foo/GeneratedWebSocket424482473.java:[56,25] illegal start of expression
[ERROR] /.../output/generated-sources/annotations/foo/GeneratedWebSocket424482473.java:[58,25] illegal start of expression
```
Here is the generated file the errors refer to:
```java
package foo;

import io.undertow.websockets.core.CloseMessage;

import java.io.IOException;

import kikaha.core.modules.http.WebResource;
import kikaha.core.modules.websocket.WebSocketHandler;
import kikaha.core.modules.websocket.WebSocketSession;
import javax.inject.Inject;
import javax.inject.Singleton;
import javax.enterprise.inject.Typed;

@Singleton
@Typed( WebSocketHandler.class )
@WebResource(  path="/chat/{room-id}/", method="GET" )
public class GeneratedWebSocket424482473 implements WebSocketHandler {

	@Inject kikaha.urouting.WebSocketDataProvider dataProvider;
	@Inject foo.ChatResource instance;

	@Override
	public void onOpen( final WebSocketSession session ) {
		try {
			instance().onOpen(
				
			
			
			);
		} catch ( final Throwable cause ) {
			onError( session, cause );
		}
	}

	@Override
	public void onText( final WebSocketSession session, final String message )
		throws IOException {
		try {
			instance().onMessage(
				
			
			,message
			
			);
		} catch ( final Throwable cause ) {
			onError( session, cause );
		}
	}

	@Override
	public void onClose( final WebSocketSession session, final CloseMessage cm ) {
		try {
			instance().onClose(
				
			
			,
			
			);
		} catch ( final Throwable cause ) {
			onError( session, cause );
		}
	}
	
	void onError( final WebSocketSession session, final Throwable cause ) {
		try {
			instance().onError(
				
			cause
			
			);
		} catch ( final Throwable e ) {
			e.printStackTrace();
		}
	}

	final foo.ChatResource instance() {
		return instance;
	}
}
```

It appears there are some errant commas being included in the generated source, such as with `instance().onMessage(,message);`, which is triggering the illegal start of expression error. Please let me know if you're able to reproduce this, in case something is wrong with my environment, etc. Thanks.

**Comment by miere** [comment]
Hi @fohara Thank you so much for your feedback.
It really sounds like a bug. I will give a try on your sample code in next few hours.
If I confirm it is a bug, I will release the 2.0.0-beta5 with this fix, okay?

Also, thank you so much for the feedback using the 2.0.0 version.
The 2.0.0 I'm still rewriting it to fit the new features... If your found any topic that sounds confused, messy or hard to understand, please fill free to open a new issue regarding to this.

Regards

**Comment by miere** [comment]
Hi @fohara I just gave your sample a try with 2.0.0-beta5 (a version I was working on this weekend) and it worked as expect, but with different imports that was written at the current 2.0.0 documentation. 

Bellow is my test source code. Would you mind to test your code with latest version I'd just pushed into the repository?

```java
import io.undertow.websockets.core.CloseMessage;
import kikaha.core.modules.websocket.WebSocketSession;
import kikaha.urouting.api.*;

@WebSocket( "chat-room" )
public class WebSocketSample {

	@OnMessage
	public void onMessage(WebSocketSession session, String message ) {
		session.broadcast( message );
	}

	@OnOpen
	public void onOpen( WebSocketSession session ) {
		session.broadcast( "New user has entered into the chat room" );
	}

	@OnError
	public void onError( final Throwable cause ) {
		System.err.println( cause.getMessage() );
	}

	@OnClose
	public void onClose( WebSocketSession session, CloseMessage cm ) {
		session.broadcast( "A user left the chat room: " + cm.getReason() );
	}
}
```

```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>WebSocket Sample</title>

	<style>

		fieldset { border: 1px solid #eee; padding: 15px 20px; }
		fieldset #name { width: 200px; display: block; margin-bottom: 10px; }
		fieldset #text { width: 300px; }

		ul li .msg-author { display: inline-block; margin-right: 10px; font-weight: bold; }
		ul li .msg-author:after { content: ":" }

	</style>

	<script language="JavaScript">

		var msgs = null, connection = null

		function configure_chat(){
			msgs = document.getElementById( 'messages' )
			connect_to_server()
			document.getElementById( 'send_button' ).addEventListener( 'click', send_message )
		}

		function connect_to_server(){
			connection = new WebSocket('ws://localhost:9000/chat-room')
			connection.onopen = function () {}
			connection.onerror = function (error) {}
			connection.onmessage = on_message_received
		}

		function on_message_received( msg ){
			msg = msg.data.split(':')
			var author = msg[0], text = msg[1]

			var li = document.createElement( 'li' )
			if ( text )
				li.appendChild( create_element( 'span', 'msg-author', author ) )
			li.appendChild( create_element( 'span', 'msg-text', text || author ) )

			msgs.appendChild( li )
		}

		function create_element( name, className, msg ){
			var e = document.createElement( name )
			e.className = className
			e.innerText = msg
			return e
		}

		function send_message(){
			var author = document.getElementById( 'name' ).value
			var text = document.getElementById( 'text' ).value
			connection.send( author + ':' + text )
		}

	</script>
</head>
<body onload="configure_chat()">

	<fieldset>
		<input id="name" placeholder="Your name goes here...">
		<input id="text" placeholder="Type a message...">
		<button id="send_button">Send</button>
	</fieldset>

	<ul id="messages"></ul>
</body>
</html>
```

**Comment by fohara** [comment]
@miere thanks for the code sample. I was able to successfully build 2.0.0-beta5, but I was unable to correctly configure my maven file to use the locally built dependencies and plugins. Is there a more straightforward way to generate a kikaha project using the locally compiled jars?

**Comment by miere** [comment]
Sure! Once you have success building the source code, you have two options. If you have created your project through the command line, you can simply type the following command on your terminal:
```shell
kikaha project use 2.0.0-beta5
```

There is also a second approach, just in case you created your project as a Maven Project. Basically, you can edit your ```pom.xml``` and change the ```parent``` section to something like the following lines:
```xml
  <parent>
    <groupId>io.skullabs.kikaha</groupId>
    <artifactId>kikaha-project</artifactId>
    <!-- here you should change from 2.0.0-beta4 to 2.0.0-beta5 -->
    <version>2.0.0-beta5</version>
  </parent>
```
Under the hood, the CLI does exactly the same on your pom.xml.
Let me know if everything went right, okay?

**Comment by fohara** [comment]
@miere I tried the two approaches you suggested above to get the project to use the local 2.0.0-beta5 artifacts, but I unfortunately couldn't get it to work. It's probably some obvious maven config I'm missing. No problem though, I can just wait until the new version is on maven central and try again then. Thanks.

**Comment by miere** [comment]
Okay @fohara. Thank you for your patience. I should release it quite soon. Probably tomorrow. I will notify you as soon as it is released to the central repository.

**Comment by miere** [comment]
@fohara We can't close the 2.0.0-beta5 version until now. Sorry for the delayed reply for your previous comment. I do think you can test it easily now.

Btw, we shall release some sample codes before the 2.0.0 final release. Would you be interested that I notify you when I release it? I do think it could provide you a better experience testing Kikaha!

**Comment by miere** [comment]
Hi @fohara 

It has been a while since our last contact. Since then, we were able to release the 2.0.x release.
I'm really interested to know if you are able to run your Web Socket app with this new release improvements.

**Comment by fohara** [comment]
@miere thanks for the update! I just tried to run a WebSocket example based on the updated docs ( http://get.kikaha.io/docs/web-socket-routing ), and it worked perfectly, so this resolves my issue 👍  . Thanks again for your help, and I'm looking forward to further testing out Kikaha.

**Comment by miere** [comment]
Nice. Thank you for your feedback and also for reporting this issue too.
Regards!!!
