### ISSUE TITLE
Graylog integration

### ISSUE THREAD

**Issue by Ibratan** [Skullabs/kikaha#183]
It would be nice if we have Kikaha's integrated with Graylog.
I'd suggest you to send data like Exceptions and HTTP Requests to it. This way we would be able to investigate possible production issues more easily. Nowadays, we have some in-house libs to achieve the same results, but maintaining it have taken several hours from our developers.

**Comment by miere** [comment]
Hi @Ibratan 

Apparently, you can use [this](https://github.com/rkcpi/logback-gelf-appender) appender to logs messages to a GELF server like Graylog2 or logstash.
It's using the official GELF Java client to connect to a remote server.

Regards
