### ISSUE TITLE
CORS requests aren't returning response headers on Google Chrome

### ISSUE THREAD

**Issue by sizebay** [Skullabs/kikaha#184]

**Comment by miere** [comment]
Hi @sizebay 
Can you please send me more information about the issue you are facing on?

I most cases, users face this CORS issue when they have not previously set the **Access-Control-Request-Headers** header. Could you please confirm if that is the case. Just in case you have no clue what I'm talking about, you can find more details [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Request-Headers).

Regards

**Comment by sizebay** [comment]
Thank you for your response, @miere. We just used the _Access-Control-Request-Headers_ solution and it seems to work greatly.
