### ISSUE TITLE
uRouting (un)serializers should use byte[] instead of String

### ISSUE THREAD

**Issue by Ibratan** [Skullabs/kikaha#200]
The current Unserializer implementation uses `String` as input parameter. This may be easier to include and maintain textual serializers but makes hard (or even impossible) the inclusion of binary serializers like Protobuf and FlatBuffer.

Shouldn't Unserializers be relying on `byte[]` instead of `String`?

**Comment by miere** [comment]
Hi @Ibratan 

I'm afraid I didn't get you point here.

The actual implementation of the `kikaha.urouting.api.Unserializer` interface does not receive `String` as input parameter, but the Undertow's `HttpServerExchange` - which is how Undertow encapsulates the current request. With the HttpServerExchange you are able to choose if you read the input as `String`, as `byte[]` or even `InputStream`.

**Comment by Ibratan** [comment]
I just submitted the pull request number #201. My point here is: the serialization and, much more specifically, the unserialization process is quite fuzzy and confused. On my PR I send a propose of what would be the right way - on our point of view - to transform the byte[] into an object. I'm sorry if I didn't clarify it before, but I think it would be more simpler if I submit a sample code that illustrates my suggestion.

**Comment by miere** [comment]
@Ibratan I took a look on your PR and I could figure out what were you suggesting to me... Quite nice PR btw.

**Comment by miere** [comment]
@Ibratan I just pushed the 2.1.0-alpha7 release. Could you please give me a feedback about this?

**Comment by Ibratan** [comment]
I think is good to go! Now, with that in mind, what do you think to focus on Protocol Buffers support? I just submitted the #203 issue to talk more about this subject.
