### ISSUE TITLE
Add Protobuf support

### ISSUE THREAD

**Issue by Ibratan** [Skullabs/kikaha#203]
It would be nice to have Protobuf support on Kikaha. It would allow us to make RPC calls efficiently.

**Comment by miere** [comment]
Hi @Ibratan 

I just pushed the 2.1.0-alpha9 no maven central. This version have an alpha, but useful, Protobuf support. I'd be glad to hear your feedback about its design and how could I improve it, okay?

**Comment by miere** [comment]
Hi @Ibratan 

It has been a while since your last interation.
Since then Protobuf has been used in a few projects and I've received a great feedback from my customers.
Although I'm closing this issue, I encourage you to re-open it if you find any inconsistence for your needs.
