### ISSUE TITLE
Allow developers to use the Content-Type defined on Response.headers() to serialize the output response

### ISSUE THREAD

**Issue by miere** [Skullabs/kikaha#204]
It would allow developers to manually define the "Content-Type" on `DefaultResponse.header`, once the Content-Type is actually a HTTP Header and some devs may prefer this approach instead of `DefaultResponse.contentType`.

**Comment by jianhuiz** [comment]
It would be more consistent to have DefaultResponse.contentType and DefaultResponse.header("Content-Type", ...) behave the same.
However if someone may want to put raw data (manual encoded object entity), I think there should be an API to do it.

**Comment by miere** [comment]
> It would be more consistent to have DefaultResponse.contentType and DefaultResponse.header("Content-Type", ...) behave the same.

Yeah. I'll keep it in mind. I should apply this patch tonight. I'd be glad to hear your feedback...

> However someone may want to put raw data (manual encoded object entity), I think there should be an API to do it.

I didn't get your point here... sorry! You mean send a `byte[]` object as response?

**Comment by miere** [comment]
Last night I patched the master branch. Now both `DefaultResponse.header( "Content-Type", ... )` and `DefaultResponse.contentType( ... )` behaves exactly the same way.

**Comment by jianhuiz** [comment]
Yes, send a byte[] object as response, but I think it should be a new api function other than `entity(byte[])`, so that it will not affected by the response content type. An overload with `String` parameter could also be added for convenient.

**Comment by miere** [comment]
Hi @jianhuiz, sorry for my late reply. It has been such a busy week.
You can send bytes through the Undertow's low level API.

```java
@GET
public void sendResponse( HttpServerExchange exchange ){
     exchange.setStatusCode( 200 );
     exchange.getResponseHeaders().put( Headers.CONTENT_TYPE, "my/content-type" );
     exchange.getResponseSender().send( myBodyBytes );
}
```
