### ISSUE TITLE
JDBC Identity Manager

### ISSUE THREAD

**Issue by Ibratan** [Skullabs/kikaha#205]
Every new project we start we have to create an `IdentityManager` implementation that make a database call to verify users' credentials. It would be nice to have an `DatabaseIdentityManager` that uses the `kikaha-db` module to execute a configurable SQL query on the database and assert that users credentials are valid.

Once 2.1.0 stills alpha, we were wondering if this wouldn't be a nice improvement to this version.
What do you think, @miere ?

**Comment by miere** [comment]
I think that's a great idea. I've discussed about this with some fellas and I received a good feedback.
Here are some points of attention:
 - Stored password maybe or not beign cryptographed before they were actually stored - thus it should allow both 'clean text' and 'cryptographed' password to be checked.
 - The cryptography algorithm should be configurable
 - There should be at least two default algorithms: 'clean text' and a real safe cryptography algorithm like `SHA-512` - or something better
 - There should be an easy way to setup other cryptography algorithms...

**Comment by miere** [comment]
I've accepted your PR last week but I've forget to give you a feedback.
It was quite good, indeed. I've noticed that you didn't create a PasswordEncoder other than PlainTextPasswordEncoder, but that is okay - I will include the BCryptPasswordEncoder on the next few weeks.
