### ISSUE TITLE
Colfer serialization

### ISSUE THREAD

**Issue by Ibratan** [Skullabs/kikaha#206]
Here at Ibratan we have a lot of microservices that are latency-sensible. Most of them handle millions of requests per minute. It means, in practice, that we should be always digging for performance improvements.

Recently we took a deep look into the Colfer and it seems to [perform better then Protobuf](https://github.com/pascaldekloe/colfer/wiki/Benchmark). Are you guys interested on using it as alternative serialization algorithm to Jackson and Protobuf?

**Comment by miere** [comment]
It seems like a nice suggestion. Right now, you are the first one to request this feature and I working hard on AWS Lambda integration. But PR are always welcome. ;)
