### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by jmilagroso** [Skullabs/kikaha#225]
Hello
I am encountering a build failure while building:
```sh
$ cd ~/kikaha
$ mvn clean package install

$ [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:testCompile (default-testCompile) on project kikaha-injection-processor: Compilation failure -> [Help 1]
```

Any thoughts on this?

**Comment by miere** [comment]
Hi @jmilagroso 
Would you mind to execute the following command on your project:
```bash
$ mvn clean install -e
```
This should print more details about the issue you are facing.
Also, I would ask to upload the output log (at least the last 30 lines), then I can help you to figure out the problem...

**Comment by jmilagroso** [comment]
Hi @miere,

Thanks, `mvn clean install -e` did it.
