### ISSUE TITLE
Add trace support for uWorkers endpoints

### ISSUE THREAD

**Issue by miere** [Skullabs/kikaha#226]
There should be a way to:
- [ ] bind the current HTTP requests and a call to an uWorker endpoint
- [ ] to receive the trace identification on a uWorker endpoint

These new behaviors will trully improve the way we trace requests on Kikaha.

**Comment by Ibratan** [comment]
The latest 61f84033f8c435ba1995e7d13723edbbbbf5daa9 commit have introduced a nice feature that would make easier to trace requests on Kikaha apps. Please take a look into that.

**Comment by miere** [comment]
Awesome stuff, indeed. I think that it seems good enough to consider this issue closed (at least for 2.1.0 release).

Also, I do think that 2.2.0 could have a more detailed (and more integrated) trace mechanism.
