### ISSUE TITLE
Add Caffeine (cache) support

### ISSUE THREAD

**Issue by miere** [Skullabs/kikaha#241]

**Comment by jmilagroso** [comment]
:star: :star: :star:

**Comment by miere** [comment]
Hi @jmilagroso, I'm glad you like the idea.
You can take a look and taste [we got so far](https://github.com/Ibratan/kikaha-caffeine) on Caffeine caching support.

**Comment by jmilagroso** [comment]
This is really nice!

Although I'm still using `2.0.4`, I'll definitely look forward on using caffeine on projects. 

Thanks

**Comment by miere** [comment]
Hey, let me know if you need help to migrate to `2.1.3`! ;)

**Comment by jmilagroso** [comment]
Are there any documentation I can use? 
Or tweaking the `pom.xml` modifying the version will suffice?

Thanks

**Comment by miere** [comment]
Changing to 2.1.3 at `pom.xml` used to be enough.
There was a very little package and classes renaming since the former stable version, but it would be very intuitive to find its replacement.

Give it a try and let me know if you find any issues.
Cheers!

**Comment by miere** [comment]
I'm closing this issue once it was already solved by the community.
