### ISSUE TITLE
AWS codeploy validate.sh improvement

### ISSUE THREAD

**Issue by roneigebert** [Skullabs/kikaha#268]
The generated validate.sh file waits a fixed time (it can be changed - parameter on pom.xml) to validate if the service started. I think it can be improved:

**Current appspec.yml**
validate service step timeout: 3600 seconds

**Current validate.sh**
sleep [fixed time|default 10 seconds]
if [service if not up]{
   raise error
}

**Desired appspec.yml**
validate service step timeout: [fixed time|default 10 seconds]

**Desired validate.sh**
while [service is not UP]{
    sleep 1 second
}

**Comment by miere** [comment]
It definitely makes sense, mate. And it's quite easy to address.
Mind to send us a PR?

**Comment by miere** [comment]
Any thoughts on this, mate?

**Comment by roneigebert** [comment]
Sorry for my delay @miere. Yesterday we talked about it here (Ibratan, @jardelnovaes).. We want to send a PR soon

**Comment by roneigebert** [comment]
@miere done! https://github.com/Skullabs/kikaha/pull/277
