### ISSUE TITLE
kikaha cli link is broken

### ISSUE THREAD

**Issue by jardelnovaes** [Skullabs/kikaha#273]
The kikaha client link is broken at https://github.com/Skullabs/kikaha/wiki/kikahas-command-line-interface-tool page 

The link http://download.kikaha.io/installer is invalid and the command below doesn't work:
`curl -s http://download.kikaha.io/installer | bash	`

**Comment by miere** [comment]
Oh, I have to deprecate this. Since its creation maven wrapper got better
and stable. Now it is the preferable tool for that job.

I shall create an archetype for new projects though. Otherwise people will
have to create projects manually.
