### ISSUE TITLE
Maven Wrapper - mvnw for Windows is absent

### ISSUE THREAD

**Issue by jardelnovaes** [Skullabs/kikaha#274]
Add mvnw for Windows

mvnw for linux is found, but not for Windows (mvnw.cmd)

**Comment by miere** [comment]
@jardelnovaes I noticed you've reopened this issue, but you haven't included any reason why.
Do you mind to elaborate more on that, mate?

**Comment by jardelnovaes** [comment]
@miere 

My mistake!
I thought I should keep it opened until the version be released.
I'm going to close it again.
