### ISSUE TITLE
AWS CodeDeploy - config to ignore stop step errors

### ISSUE THREAD

**Issue by roneigebert** [Skullabs/kikaha#279]
For blue/green deployments it's usefull to use the "withIgnoreApplicationStopFailures" method to ignore any errors in old instances (before/after/blocktraffic) - sometimes erros occur when scaling activity and deploy are running at the same time.

https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/codedeploy/model/CreateDeploymentRequest.html#withIgnoreApplicationStopFailures-java.lang.Boolean-

**Comment by miere** [comment]
I think this is a good improvement.
How shall we proceed? Can we pair together on this and get this issue solved?
I'm keen to wrap a new release of Kikaha for this week.

**Comment by roneigebert** [comment]
@miere what about a boolean flag "ignoreApplicationStopFailures" on KikahaS3DeployerMojo with default "false"?

**Comment by miere** [comment]
I think that's a sensible solution. The default behaviour, in this case, makes sense to be more strict (set to false). People can relax this behaviour by setting it to true.

**Comment by roneigebert** [comment]
@miere done! https://github.com/Skullabs/kikaha/pull/277
